#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    mobileLowerAngle, sensorPotentiometer)
#pragma config(Sensor, in2,    mobileHigherAngle, sensorPotentiometer)
#pragma config(Sensor, in3,    coneAngle,      sensorPotentiometer)
#pragma config(Sensor, I2C_1,  leftDrive,      sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  rightDrive,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           driveBackLeft, tmotorVex393HighSpeed_HBridge, openLoop, reversed, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port2,           driveFrontLeft, tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           liftMobileLowerLeft, tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           liftMobileHigherLeft, tmotorVex393HighSpeed_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port5,           liftConeLeft,  tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port6,           liftConeRight, tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port7,           liftMobileHigherRight, tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port8,           liftMobileLowerRight, tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port9,           driveFrontRight, tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          driveBackRight, tmotorVex393HighSpeed_HBridge, openLoop, driveRight, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("Sensors")
#pragma DebuggerWindows("Motors")
#pragma DebuggerWindows("Locals")
#pragma DebuggerWindows("Globals")

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "driveFunctions.c"

bool mobileLowerIfTrue = true;

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		/*
		Drive
		Calls driveFunctions program to change motor speeds
		*/
		setMotorSpeed(vexRT[Ch2], vexRT[Ch3]);

		/*
		Lift Program
		This controls the 3 lift systems
		They will be split into 2 sections, the Mobile Goal Lifts and the Cone Lift
		*/
		//Set Mobile Higher or Lower
		if(vexRT[Btn7D] == 1){
			mobileLowerIfTrue = true;
		}
		else if(vexRT[Btn7L] == 1){
			mobileLowerIfTrue = false;
		}
		//Mobile Goal Lift
		/*if(vexRT[Btn5U] == 1){
			//if(mobileLowerIfTrue && SensorValue[mobileLowerAngle] < 3600){

			//}
			else if(SensorValue[mobileHigherAngle] < 3600){
				motor[liftMobileHigherLeft] = 127;
				motor[liftMobileHigherRight] = 127;
			}
				motor[liftMobileLowerLeft] = 127;
				motor[liftMobileLowerRight] = 127;
		}
		else if(vexRT[Btn5D] == 1){
			if(mobileLowerIfTrue && SensorValue[mobileLowerAngle] > 360){
				motor[liftMobileLowerLeft] = -67;
				motor[liftMobileLowerRight] = -67;
			}
			else if(SensorValue[mobileHigherAngle] > 360){
				motor[liftMobileHigherLeft] = -67;
				motor[liftMobileHigherRight] = -67;
			}
		}
		else{
			motor[liftMobileLowerLeft] = 0;
			motor[liftMobileLowerRight] = 0;
			motor[liftMobileHigherLeft] = 0;
			motor[liftMobileHigherRight] = 0;
		}*/

		//low lift
		if(vexRT[Btn5U]){
		while(SensorValue[mobileLowerAngle] < 3100){
			//goes up
			motor[liftMobileLowerLeft] = 127;
			motor[liftMobileLowerRight] = 127;
		}
	}else if(vexRT[Btn5D]){
		while(SensorValue[mobileLowerAngle] > 2500){
			//goes down
			motor[liftMobileLowerLeft] = -127;
			motor[liftMobileLowerRight] = -127;
		}
	}else{
			motor[liftMobileLowerLeft] = 0;
			motor[liftMobileLowerRight] = 0;
	}



		//High lift
	if(vexRT[Btn6U]){
		//while(SensorValue[mobileHigherAngle] < 4100){
			//goes up
			motor[liftMobileHigherLeft] = 127;
			motor[liftMobileHigherRight] = 127;
		//}
	}else if(vexRT[Btn6D]){
		//while(SensorValue[mobileHigherAngle] > 700){
			//goes down
			motor[liftMobileHigherLeft] = -127;
			motor[liftMobileHigherRight] = -127;
	//	}
	}else{
			motor[liftMobileHigherLeft] = 0;
			motor[liftMobileHigherRight] = 0;
	}





		/*Cone Lift
		if(vexRT[Btn6U] == 1 && SensorValue[mobileHigherAngle] < 3600){
			motor[liftConeLeft] = 127;
			motor[liftConeRight] = 127;
		}
		else if(vexRT[Btn6D] == 1 && SensorValue[mobileHigherAngle] > 360){
			motor[liftConeLeft] = -127;
			motor[liftConeRight] = -127;
		}
		else{
			motor[liftConeLeft] = 0;
			motor[liftConeRight] = 0;
		}*/
	}
}